# Generated by Django 4.1.3 on 2023-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ScraperApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(default="scraper_users", max_length=254),
        ),
    ]
