# Generated by Django 4.1.3 on 2023-05-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ScraperApp", "0002_users_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="Scrapers",
        ),
    ]
