# Generated by Django 3.2 on 2023-08-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperApp', '0003_rename_users_scrapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt_id', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateField()),
                ('tshirt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScraperApp.tshirt')),
            ],
        ),
    ]
