# Generated by Django 3.2 on 2023-08-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperApp', '0004_sales_tshirt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
