# Generated by Django 3.2 on 2023-09-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperApp', '0006_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
